version: "3.9"

services:
  go-app:
    container_name: studying-golang
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - go_db

  go_db:
    container_name: fo_db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
